export const GET_USER_NOTIFICATIONS = 'notifications/GET_USER_NOTIFICATIONS'
export const ADD_NOTIFICATION = 'notifications/ADD_NOTIFICATION'
export const MARK_NOTIFICATION_AS_READ = 'notifications/MARK_NOTIFICATION_AS_READ'
