export const CLEAN_STATE = 'board/CLEAN_STATE'
export const GET_ALL_LISTS_IN_BOARD = 'board/GET_ALL_LISTS_IN_BOARD'
export const GET_ALL_LABELS_IN_BOARD = 'board/GET_ALL_LABELS_IN_BOARD'
export const GET_ONE_BOARD = 'board/GET_ONE_BOARD'
export const SAVE_BOARD_TITLE = 'board/SAVE_BOARD_TITLE'
