export const GET_BOARD_OWNER = 'boardMembers/GET_BOARD_OWNER'
export const GET_BOARD_CONTRIBUTORS = 'boardMembers/GET_BOARD_CONTRIBUTORS'
export const ADD_CONTRIBUTOR_TO_BOARD = 'boardMembers/ADD_CONTRIBUTOR_TO_BOARD'
export const REMOVE_CONTRIBUTOR_FROM_BOARD = 'boardMembers/REMOVE_CONTRIBUTOR_FROM_BOARD'
