export const CLEAN_STATE = 'cards/CLEAN_STATE'
export const ADD_CARD = 'cards/ADD_CARD'
export const DELETE_CARD = 'cards/DELETE_CARD'
export const GET_ALL_CARDS_IN_LIST = 'cards/GET_ALL_CARDS_IN_LIST'
export const SAVE_CARD_RANK = 'cards/SAVE_CARD_RANK'
export const SAVE_CARD_TITLE = 'cards/SAVE_CARD_TITLE'
